### ISSUE TITLE
Incompatibility with PITest 1.4.3

### ISSUE THREAD

**Issue by dmitry-timofeev** [STAMP-project/pitmp-maven-plugin#35]
Hi, cool project! I've encountered an incompatibility with the recent PITest:

#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: 1.3.6
- **Execution Environment**: Oracle JDK 8, Maven 3.5.4, Ubuntu 16.04

#### Description
Such configuration
```
      <plugin>
        <groupId>eu.stamp-project</groupId>
        <artifactId>pitmp-maven-plugin</artifactId>
        <version>1.3.6</version>
        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <version>1.4.3</version>
          </dependency>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-junit5-plugin</artifactId>
            <version>0.7</version>
          </dependency>
        </dependencies>
      </plugin>
```
causes the build to fail with the following error:
```
[ERROR] Failed to execute goal eu.stamp-project:pitmp-maven-plugin:1.3.6:run (default-cli) on project foo: Execution default-cli of goal eu.stamp-project:pitmp-maven-plugin:1.3.6:run failed: An API incompatibility was encountered while executing eu.stamp-project:pitmp-maven-plugin:1.3.6:run: java.lang.NoSuchMethodError: org.pitest.mutationtest.config.ReportOptions.setFullMutationMatrix(Z)V
```

Works fine with 1.4.2.

**Comment by pedrorijo91** [comment]
this supported versions are documented under https://github.com/STAMP-project/pitmp-maven-plugin#releases

**Comment by oscarlvp** [comment]
1.3.7-SNAPSHOT has been deployed to the [Nexus repository](https://oss.sonatype.org/#nexus-search;quick~pitmp-maven-plugin) and should address this issue.
