### PR TITLE
Bump pit dependency to 1.4.3

### LINKED ISSUE #35: Incompatibility with PITest 1.4.3
Hi, cool project! I've encountered an incompatibility with the recent PITest:

#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: 1.3.6
- **Execution Environment**: Oracle JDK 8, Maven 3.5.4, Ubuntu 16.04

#### Description
Such configuration
```
      <plugin>
        <groupId>eu.stamp-project</groupId>
        <artifactId>pitmp-maven-plugin</artifactId>
        <version>1.3.6</version>
        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <version>1.4.3</version>
          </dependency>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-junit5-plugin</artifactId>
            <version>0.7</version>
          </dependency>
        </dependencies>
      </plugin>
```
causes the build to fail with the following error:
```
[ERROR] Failed to execute goal eu.stamp-project:pitmp-maven-plugin:1.3.6:run (default-cli) on project foo: Execution default-cli of goal eu.stamp-project:pitmp-maven-plugin:1.3.6:run failed: An API incompatibility was encountered while executing eu.stamp-project:pitmp-maven-plugin:1.3.6:run: java.lang.NoSuchMethodError: org.pitest.mutationtest.config.ReportOptions.setFullMutationMatrix(Z)V
```

Works fine with 1.4.2.

### PR DESCRIPTION
**Pull request by pedrorijo91**
closes #35

### CODE REVIEW

**Comment by pedrorijo91** [comment]
I guess this PR doesn't make sense anymore
