### ISSUE TITLE
pitmp does not work with pitest 1.3.2

### ISSUE THREAD

**Issue by n-a-sz** [STAMP-project/pitmp-maven-plugin#7]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: pitmp-maven-plugin 1.1.1
- **Execution Environment**:  Win10, maven 3.5.3, pitest 1.3.2
- **Reporter**: András Szabolcs Nagy

#### Description
I got the following exception:

Failed to execute goal eu.stamp:pitmp-maven-plugin:1.1.1:run (default-cli) on project XXX: Execution default-cli of goal eu.stamp:pitmp-maven-plugin:1.1.1:run failed: An API incompatibility was encountered while executing eu.stamp:pitmp-maven-plugin:1.1.1:run: java.lang.NoSuchMethodError: org.pitest.mutationtest.config.ReportOptions.setIncludedTestMethods(Ljava/util/Collection;)V

**Comment by McKratt** [comment]
+1

- **Tool/Service/Component :** pitmp-maven-plugin 1.1.4

- **Exécution Environnement :** OSX 10.13.4, Maven 3.3.9

**Comment by Cael35** [comment]
This issue should be fixed in the release 1.1.5 available in Maven Central, but I tested only on Ubuntu 16.04.4 LTS. I will try to test on Windows and OSX. :-)

**Comment by McKratt** [comment]
I confirm version 1.1.5 works on OSX 10.13.4, Maven 3.3.9 and JDK 1.8_111

**Comment by Cael35** [comment]
Thanks ! :-)
